// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface ChambreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Chambre)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string prix = 2;</code>
   * @return The prix.
   */
  java.lang.String getPrix();
  /**
   * <code>string prix = 2;</code>
   * @return The bytes for prix.
   */
  com.google.protobuf.ByteString
      getPrixBytes();

  /**
   * <code>bool disponible = 3;</code>
   * @return The disponible.
   */
  boolean getDisponible();

  /**
   * <code>.TypeChambre type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.TypeChambre type = 4;</code>
   * @return The type.
   */
  com.project.booking.stubs.TypeChambre getType();
}
