// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface deleteReservationByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deleteReservationByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.DeleteReservationResult deleted = 1;</code>
   * @return Whether the deleted field is set.
   */
  boolean hasDeleted();
  /**
   * <code>.DeleteReservationResult deleted = 1;</code>
   * @return The deleted.
   */
  com.project.booking.stubs.DeleteReservationResult getDeleted();
  /**
   * <code>.DeleteReservationResult deleted = 1;</code>
   */
  com.project.booking.stubs.DeleteReservationResultOrBuilder getDeletedOrBuilder();
}
