// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface deleteReservationByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deleteReservationByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.DeleteCompteResult deleted = 1;</code>
   * @return Whether the deleted field is set.
   */
  boolean hasDeleted();
  /**
   * <code>.DeleteCompteResult deleted = 1;</code>
   * @return The deleted.
   */
  com.project.booking.stubs.DeleteCompteResult getDeleted();
  /**
   * <code>.DeleteCompteResult deleted = 1;</code>
   */
  com.project.booking.stubs.DeleteCompteResultOrBuilder getDeletedOrBuilder();
}
