// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface getAllchambresRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getAllchambresRequest)
    com.google.protobuf.MessageOrBuilder {
}
