// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface getAllPreferencesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getAllPreferencesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Preference preferences = 1;</code>
   */
  java.util.List<com.project.booking.stubs.Preference> 
      getPreferencesList();
  /**
   * <code>repeated .Preference preferences = 1;</code>
   */
  com.project.booking.stubs.Preference getPreferences(int index);
  /**
   * <code>repeated .Preference preferences = 1;</code>
   */
  int getPreferencesCount();
  /**
   * <code>repeated .Preference preferences = 1;</code>
   */
  java.util.List<? extends com.project.booking.stubs.PreferenceOrBuilder> 
      getPreferencesOrBuilderList();
  /**
   * <code>repeated .Preference preferences = 1;</code>
   */
  com.project.booking.stubs.PreferenceOrBuilder getPreferencesOrBuilder(
      int index);
}
