// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface getAllPreferencesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getAllPreferencesRequest)
    com.google.protobuf.MessageOrBuilder {
}
