// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface getAllchambresResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getAllchambresResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  java.util.List<com.project.booking.stubs.Chambre> 
      getChambresList();
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  com.project.booking.stubs.Chambre getChambres(int index);
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  int getChambresCount();
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  java.util.List<? extends com.project.booking.stubs.ChambreOrBuilder> 
      getChambresOrBuilderList();
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  com.project.booking.stubs.ChambreOrBuilder getChambresOrBuilder(
      int index);
}
