// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

/**
 * <pre>
 * Réponse contenant la liste des chambres
 * </pre>
 *
 * Protobuf type {@code getAllchambresResponse}
 */
public  final class getAllchambresResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:getAllchambresResponse)
    getAllchambresResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use getAllchambresResponse.newBuilder() to construct.
  private getAllchambresResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private getAllchambresResponse() {
    chambres_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new getAllchambresResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private getAllchambresResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              chambres_ = new java.util.ArrayList<com.project.booking.stubs.Chambre>();
              mutable_bitField0_ |= 0x00000001;
            }
            chambres_.add(
                input.readMessage(com.project.booking.stubs.Chambre.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        chambres_ = java.util.Collections.unmodifiableList(chambres_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.project.booking.stubs.ReservationOuterClass.internal_static_getAllchambresResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.project.booking.stubs.ReservationOuterClass.internal_static_getAllchambresResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.project.booking.stubs.getAllchambresResponse.class, com.project.booking.stubs.getAllchambresResponse.Builder.class);
  }

  public static final int CHAMBRES_FIELD_NUMBER = 1;
  private java.util.List<com.project.booking.stubs.Chambre> chambres_;
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  public java.util.List<com.project.booking.stubs.Chambre> getChambresList() {
    return chambres_;
  }
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  public java.util.List<? extends com.project.booking.stubs.ChambreOrBuilder> 
      getChambresOrBuilderList() {
    return chambres_;
  }
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  public int getChambresCount() {
    return chambres_.size();
  }
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  public com.project.booking.stubs.Chambre getChambres(int index) {
    return chambres_.get(index);
  }
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  public com.project.booking.stubs.ChambreOrBuilder getChambresOrBuilder(
      int index) {
    return chambres_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < chambres_.size(); i++) {
      output.writeMessage(1, chambres_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < chambres_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, chambres_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.project.booking.stubs.getAllchambresResponse)) {
      return super.equals(obj);
    }
    com.project.booking.stubs.getAllchambresResponse other = (com.project.booking.stubs.getAllchambresResponse) obj;

    if (!getChambresList()
        .equals(other.getChambresList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getChambresCount() > 0) {
      hash = (37 * hash) + CHAMBRES_FIELD_NUMBER;
      hash = (53 * hash) + getChambresList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.project.booking.stubs.getAllchambresResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.project.booking.stubs.getAllchambresResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.project.booking.stubs.getAllchambresResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.project.booking.stubs.getAllchambresResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.project.booking.stubs.getAllchambresResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.project.booking.stubs.getAllchambresResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.project.booking.stubs.getAllchambresResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.project.booking.stubs.getAllchambresResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.project.booking.stubs.getAllchambresResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.project.booking.stubs.getAllchambresResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.project.booking.stubs.getAllchambresResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.project.booking.stubs.getAllchambresResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.project.booking.stubs.getAllchambresResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Réponse contenant la liste des chambres
   * </pre>
   *
   * Protobuf type {@code getAllchambresResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:getAllchambresResponse)
      com.project.booking.stubs.getAllchambresResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.booking.stubs.ReservationOuterClass.internal_static_getAllchambresResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.booking.stubs.ReservationOuterClass.internal_static_getAllchambresResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.booking.stubs.getAllchambresResponse.class, com.project.booking.stubs.getAllchambresResponse.Builder.class);
    }

    // Construct using com.project.booking.stubs.getAllchambresResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getChambresFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (chambresBuilder_ == null) {
        chambres_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        chambresBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.project.booking.stubs.ReservationOuterClass.internal_static_getAllchambresResponse_descriptor;
    }

    @java.lang.Override
    public com.project.booking.stubs.getAllchambresResponse getDefaultInstanceForType() {
      return com.project.booking.stubs.getAllchambresResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.project.booking.stubs.getAllchambresResponse build() {
      com.project.booking.stubs.getAllchambresResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.project.booking.stubs.getAllchambresResponse buildPartial() {
      com.project.booking.stubs.getAllchambresResponse result = new com.project.booking.stubs.getAllchambresResponse(this);
      int from_bitField0_ = bitField0_;
      if (chambresBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          chambres_ = java.util.Collections.unmodifiableList(chambres_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.chambres_ = chambres_;
      } else {
        result.chambres_ = chambresBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.project.booking.stubs.getAllchambresResponse) {
        return mergeFrom((com.project.booking.stubs.getAllchambresResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.project.booking.stubs.getAllchambresResponse other) {
      if (other == com.project.booking.stubs.getAllchambresResponse.getDefaultInstance()) return this;
      if (chambresBuilder_ == null) {
        if (!other.chambres_.isEmpty()) {
          if (chambres_.isEmpty()) {
            chambres_ = other.chambres_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChambresIsMutable();
            chambres_.addAll(other.chambres_);
          }
          onChanged();
        }
      } else {
        if (!other.chambres_.isEmpty()) {
          if (chambresBuilder_.isEmpty()) {
            chambresBuilder_.dispose();
            chambresBuilder_ = null;
            chambres_ = other.chambres_;
            bitField0_ = (bitField0_ & ~0x00000001);
            chambresBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChambresFieldBuilder() : null;
          } else {
            chambresBuilder_.addAllMessages(other.chambres_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.project.booking.stubs.getAllchambresResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.project.booking.stubs.getAllchambresResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.project.booking.stubs.Chambre> chambres_ =
      java.util.Collections.emptyList();
    private void ensureChambresIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        chambres_ = new java.util.ArrayList<com.project.booking.stubs.Chambre>(chambres_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.project.booking.stubs.Chambre, com.project.booking.stubs.Chambre.Builder, com.project.booking.stubs.ChambreOrBuilder> chambresBuilder_;

    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public java.util.List<com.project.booking.stubs.Chambre> getChambresList() {
      if (chambresBuilder_ == null) {
        return java.util.Collections.unmodifiableList(chambres_);
      } else {
        return chambresBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public int getChambresCount() {
      if (chambresBuilder_ == null) {
        return chambres_.size();
      } else {
        return chambresBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public com.project.booking.stubs.Chambre getChambres(int index) {
      if (chambresBuilder_ == null) {
        return chambres_.get(index);
      } else {
        return chambresBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public Builder setChambres(
        int index, com.project.booking.stubs.Chambre value) {
      if (chambresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChambresIsMutable();
        chambres_.set(index, value);
        onChanged();
      } else {
        chambresBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public Builder setChambres(
        int index, com.project.booking.stubs.Chambre.Builder builderForValue) {
      if (chambresBuilder_ == null) {
        ensureChambresIsMutable();
        chambres_.set(index, builderForValue.build());
        onChanged();
      } else {
        chambresBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public Builder addChambres(com.project.booking.stubs.Chambre value) {
      if (chambresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChambresIsMutable();
        chambres_.add(value);
        onChanged();
      } else {
        chambresBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public Builder addChambres(
        int index, com.project.booking.stubs.Chambre value) {
      if (chambresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChambresIsMutable();
        chambres_.add(index, value);
        onChanged();
      } else {
        chambresBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public Builder addChambres(
        com.project.booking.stubs.Chambre.Builder builderForValue) {
      if (chambresBuilder_ == null) {
        ensureChambresIsMutable();
        chambres_.add(builderForValue.build());
        onChanged();
      } else {
        chambresBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public Builder addChambres(
        int index, com.project.booking.stubs.Chambre.Builder builderForValue) {
      if (chambresBuilder_ == null) {
        ensureChambresIsMutable();
        chambres_.add(index, builderForValue.build());
        onChanged();
      } else {
        chambresBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public Builder addAllChambres(
        java.lang.Iterable<? extends com.project.booking.stubs.Chambre> values) {
      if (chambresBuilder_ == null) {
        ensureChambresIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, chambres_);
        onChanged();
      } else {
        chambresBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public Builder clearChambres() {
      if (chambresBuilder_ == null) {
        chambres_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        chambresBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public Builder removeChambres(int index) {
      if (chambresBuilder_ == null) {
        ensureChambresIsMutable();
        chambres_.remove(index);
        onChanged();
      } else {
        chambresBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public com.project.booking.stubs.Chambre.Builder getChambresBuilder(
        int index) {
      return getChambresFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public com.project.booking.stubs.ChambreOrBuilder getChambresOrBuilder(
        int index) {
      if (chambresBuilder_ == null) {
        return chambres_.get(index);  } else {
        return chambresBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public java.util.List<? extends com.project.booking.stubs.ChambreOrBuilder> 
         getChambresOrBuilderList() {
      if (chambresBuilder_ != null) {
        return chambresBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(chambres_);
      }
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public com.project.booking.stubs.Chambre.Builder addChambresBuilder() {
      return getChambresFieldBuilder().addBuilder(
          com.project.booking.stubs.Chambre.getDefaultInstance());
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public com.project.booking.stubs.Chambre.Builder addChambresBuilder(
        int index) {
      return getChambresFieldBuilder().addBuilder(
          index, com.project.booking.stubs.Chambre.getDefaultInstance());
    }
    /**
     * <code>repeated .Chambre chambres = 1;</code>
     */
    public java.util.List<com.project.booking.stubs.Chambre.Builder> 
         getChambresBuilderList() {
      return getChambresFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.project.booking.stubs.Chambre, com.project.booking.stubs.Chambre.Builder, com.project.booking.stubs.ChambreOrBuilder> 
        getChambresFieldBuilder() {
      if (chambresBuilder_ == null) {
        chambresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.project.booking.stubs.Chambre, com.project.booking.stubs.Chambre.Builder, com.project.booking.stubs.ChambreOrBuilder>(
                chambres_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        chambres_ = null;
      }
      return chambresBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:getAllchambresResponse)
  }

  // @@protoc_insertion_point(class_scope:getAllchambresResponse)
  private static final com.project.booking.stubs.getAllchambresResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.project.booking.stubs.getAllchambresResponse();
  }

  public static com.project.booking.stubs.getAllchambresResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<getAllchambresResponse>
      PARSER = new com.google.protobuf.AbstractParser<getAllchambresResponse>() {
    @java.lang.Override
    public getAllchambresResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new getAllchambresResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<getAllchambresResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<getAllchambresResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.project.booking.stubs.getAllchambresResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

