// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface getAllChambresRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getAllChambresRequest)
    com.google.protobuf.MessageOrBuilder {
}
