// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface getReservationByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getReservationByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  com.project.booking.stubs.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  com.project.booking.stubs.ReservationOrBuilder getReservationOrBuilder();
}
