// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface PreferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Preference)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string nom = 2;</code>
   * @return The nom.
   */
  java.lang.String getNom();
  /**
   * <code>string nom = 2;</code>
   * @return The bytes for nom.
   */
  com.google.protobuf.ByteString
      getNomBytes();
}
