// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface PreferenceDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PreferenceDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nom = 1;</code>
   * @return The nom.
   */
  java.lang.String getNom();
  /**
   * <code>string nom = 1;</code>
   * @return The bytes for nom.
   */
  com.google.protobuf.ByteString
      getNomBytes();
}
