// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface ReservationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Reservation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string dateDebut = 2;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <code>string dateDebut = 2;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <code>string dateFin = 3;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <code>string dateFin = 3;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();

  /**
   * <code>.Chambre chambre = 4;</code>
   * @return Whether the chambre field is set.
   */
  boolean hasChambre();
  /**
   * <code>.Chambre chambre = 4;</code>
   * @return The chambre.
   */
  com.project.booking.stubs.Chambre getChambre();
  /**
   * <code>.Chambre chambre = 4;</code>
   */
  com.project.booking.stubs.ChambreOrBuilder getChambreOrBuilder();

  /**
   * <code>.Client client = 5;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.Client client = 5;</code>
   * @return The client.
   */
  com.project.booking.stubs.Client getClient();
  /**
   * <code>.Client client = 5;</code>
   */
  com.project.booking.stubs.ClientOrBuilder getClientOrBuilder();

  /**
   * <pre>
   * Champ repeated pour les préférences
   * </pre>
   *
   * <code>repeated .Preference preferences = 6;</code>
   */
  java.util.List<com.project.booking.stubs.Preference> 
      getPreferencesList();
  /**
   * <pre>
   * Champ repeated pour les préférences
   * </pre>
   *
   * <code>repeated .Preference preferences = 6;</code>
   */
  com.project.booking.stubs.Preference getPreferences(int index);
  /**
   * <pre>
   * Champ repeated pour les préférences
   * </pre>
   *
   * <code>repeated .Preference preferences = 6;</code>
   */
  int getPreferencesCount();
  /**
   * <pre>
   * Champ repeated pour les préférences
   * </pre>
   *
   * <code>repeated .Preference preferences = 6;</code>
   */
  java.util.List<? extends com.project.booking.stubs.PreferenceOrBuilder> 
      getPreferencesOrBuilderList();
  /**
   * <pre>
   * Champ repeated pour les préférences
   * </pre>
   *
   * <code>repeated .Preference preferences = 6;</code>
   */
  com.project.booking.stubs.PreferenceOrBuilder getPreferencesOrBuilder(
      int index);
}
