// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface ReservationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Reservation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string dateDebut = 2;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <code>string dateDebut = 2;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <code>string dateFin = 3;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <code>string dateFin = 3;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();

  /**
   * <code>.Client client = 4;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.Client client = 4;</code>
   * @return The client.
   */
  com.project.booking.stubs.Client getClient();
  /**
   * <code>.Client client = 4;</code>
   */
  com.project.booking.stubs.ClientOrBuilder getClientOrBuilder();

  /**
   * <code>.Chambre chambre = 5;</code>
   * @return Whether the chambre field is set.
   */
  boolean hasChambre();
  /**
   * <code>.Chambre chambre = 5;</code>
   * @return The chambre.
   */
  com.project.booking.stubs.Chambre getChambre();
  /**
   * <code>.Chambre chambre = 5;</code>
   */
  com.project.booking.stubs.ChambreOrBuilder getChambreOrBuilder();

  /**
   * <code>.Preference preference = 6;</code>
   * @return Whether the preference field is set.
   */
  boolean hasPreference();
  /**
   * <code>.Preference preference = 6;</code>
   * @return The preference.
   */
  com.project.booking.stubs.Preference getPreference();
  /**
   * <code>.Preference preference = 6;</code>
   */
  com.project.booking.stubs.PreferenceOrBuilder getPreferenceOrBuilder();
}
