// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

/**
 * <pre>
 * Message représentant une reservation
 * </pre>
 *
 * Protobuf type {@code Reservation}
 */
public  final class Reservation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Reservation)
    ReservationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Reservation.newBuilder() to construct.
  private Reservation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Reservation() {
    dateDebut_ = "";
    dateFin_ = "";
    preferences_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Reservation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Reservation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            dateDebut_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            dateFin_ = s;
            break;
          }
          case 34: {
            com.project.booking.stubs.Chambre.Builder subBuilder = null;
            if (chambre_ != null) {
              subBuilder = chambre_.toBuilder();
            }
            chambre_ = input.readMessage(com.project.booking.stubs.Chambre.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(chambre_);
              chambre_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.project.booking.stubs.Client.Builder subBuilder = null;
            if (client_ != null) {
              subBuilder = client_.toBuilder();
            }
            client_ = input.readMessage(com.project.booking.stubs.Client.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(client_);
              client_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              preferences_ = new java.util.ArrayList<com.project.booking.stubs.Preference>();
              mutable_bitField0_ |= 0x00000001;
            }
            preferences_.add(
                input.readMessage(com.project.booking.stubs.Preference.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        preferences_ = java.util.Collections.unmodifiableList(preferences_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.project.booking.stubs.ReservationOuterClass.internal_static_Reservation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.project.booking.stubs.ReservationOuterClass.internal_static_Reservation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.project.booking.stubs.Reservation.class, com.project.booking.stubs.Reservation.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  public long getId() {
    return id_;
  }

  public static final int DATEDEBUT_FIELD_NUMBER = 2;
  private volatile java.lang.Object dateDebut_;
  /**
   * <code>string dateDebut = 2;</code>
   * @return The dateDebut.
   */
  public java.lang.String getDateDebut() {
    java.lang.Object ref = dateDebut_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dateDebut_ = s;
      return s;
    }
  }
  /**
   * <code>string dateDebut = 2;</code>
   * @return The bytes for dateDebut.
   */
  public com.google.protobuf.ByteString
      getDateDebutBytes() {
    java.lang.Object ref = dateDebut_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dateDebut_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATEFIN_FIELD_NUMBER = 3;
  private volatile java.lang.Object dateFin_;
  /**
   * <code>string dateFin = 3;</code>
   * @return The dateFin.
   */
  public java.lang.String getDateFin() {
    java.lang.Object ref = dateFin_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dateFin_ = s;
      return s;
    }
  }
  /**
   * <code>string dateFin = 3;</code>
   * @return The bytes for dateFin.
   */
  public com.google.protobuf.ByteString
      getDateFinBytes() {
    java.lang.Object ref = dateFin_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dateFin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHAMBRE_FIELD_NUMBER = 4;
  private com.project.booking.stubs.Chambre chambre_;
  /**
   * <code>.Chambre chambre = 4;</code>
   * @return Whether the chambre field is set.
   */
  public boolean hasChambre() {
    return chambre_ != null;
  }
  /**
   * <code>.Chambre chambre = 4;</code>
   * @return The chambre.
   */
  public com.project.booking.stubs.Chambre getChambre() {
    return chambre_ == null ? com.project.booking.stubs.Chambre.getDefaultInstance() : chambre_;
  }
  /**
   * <code>.Chambre chambre = 4;</code>
   */
  public com.project.booking.stubs.ChambreOrBuilder getChambreOrBuilder() {
    return getChambre();
  }

  public static final int CLIENT_FIELD_NUMBER = 5;
  private com.project.booking.stubs.Client client_;
  /**
   * <code>.Client client = 5;</code>
   * @return Whether the client field is set.
   */
  public boolean hasClient() {
    return client_ != null;
  }
  /**
   * <code>.Client client = 5;</code>
   * @return The client.
   */
  public com.project.booking.stubs.Client getClient() {
    return client_ == null ? com.project.booking.stubs.Client.getDefaultInstance() : client_;
  }
  /**
   * <code>.Client client = 5;</code>
   */
  public com.project.booking.stubs.ClientOrBuilder getClientOrBuilder() {
    return getClient();
  }

  public static final int PREFERENCES_FIELD_NUMBER = 6;
  private java.util.List<com.project.booking.stubs.Preference> preferences_;
  /**
   * <pre>
   * Champ repeated pour les préférences
   * </pre>
   *
   * <code>repeated .Preference preferences = 6;</code>
   */
  public java.util.List<com.project.booking.stubs.Preference> getPreferencesList() {
    return preferences_;
  }
  /**
   * <pre>
   * Champ repeated pour les préférences
   * </pre>
   *
   * <code>repeated .Preference preferences = 6;</code>
   */
  public java.util.List<? extends com.project.booking.stubs.PreferenceOrBuilder> 
      getPreferencesOrBuilderList() {
    return preferences_;
  }
  /**
   * <pre>
   * Champ repeated pour les préférences
   * </pre>
   *
   * <code>repeated .Preference preferences = 6;</code>
   */
  public int getPreferencesCount() {
    return preferences_.size();
  }
  /**
   * <pre>
   * Champ repeated pour les préférences
   * </pre>
   *
   * <code>repeated .Preference preferences = 6;</code>
   */
  public com.project.booking.stubs.Preference getPreferences(int index) {
    return preferences_.get(index);
  }
  /**
   * <pre>
   * Champ repeated pour les préférences
   * </pre>
   *
   * <code>repeated .Preference preferences = 6;</code>
   */
  public com.project.booking.stubs.PreferenceOrBuilder getPreferencesOrBuilder(
      int index) {
    return preferences_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getDateDebutBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dateDebut_);
    }
    if (!getDateFinBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dateFin_);
    }
    if (chambre_ != null) {
      output.writeMessage(4, getChambre());
    }
    if (client_ != null) {
      output.writeMessage(5, getClient());
    }
    for (int i = 0; i < preferences_.size(); i++) {
      output.writeMessage(6, preferences_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getDateDebutBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dateDebut_);
    }
    if (!getDateFinBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dateFin_);
    }
    if (chambre_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getChambre());
    }
    if (client_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getClient());
    }
    for (int i = 0; i < preferences_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, preferences_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.project.booking.stubs.Reservation)) {
      return super.equals(obj);
    }
    com.project.booking.stubs.Reservation other = (com.project.booking.stubs.Reservation) obj;

    if (getId()
        != other.getId()) return false;
    if (!getDateDebut()
        .equals(other.getDateDebut())) return false;
    if (!getDateFin()
        .equals(other.getDateFin())) return false;
    if (hasChambre() != other.hasChambre()) return false;
    if (hasChambre()) {
      if (!getChambre()
          .equals(other.getChambre())) return false;
    }
    if (hasClient() != other.hasClient()) return false;
    if (hasClient()) {
      if (!getClient()
          .equals(other.getClient())) return false;
    }
    if (!getPreferencesList()
        .equals(other.getPreferencesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + DATEDEBUT_FIELD_NUMBER;
    hash = (53 * hash) + getDateDebut().hashCode();
    hash = (37 * hash) + DATEFIN_FIELD_NUMBER;
    hash = (53 * hash) + getDateFin().hashCode();
    if (hasChambre()) {
      hash = (37 * hash) + CHAMBRE_FIELD_NUMBER;
      hash = (53 * hash) + getChambre().hashCode();
    }
    if (hasClient()) {
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClient().hashCode();
    }
    if (getPreferencesCount() > 0) {
      hash = (37 * hash) + PREFERENCES_FIELD_NUMBER;
      hash = (53 * hash) + getPreferencesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.project.booking.stubs.Reservation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.project.booking.stubs.Reservation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.project.booking.stubs.Reservation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.project.booking.stubs.Reservation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.project.booking.stubs.Reservation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.project.booking.stubs.Reservation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.project.booking.stubs.Reservation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.project.booking.stubs.Reservation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.project.booking.stubs.Reservation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.project.booking.stubs.Reservation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.project.booking.stubs.Reservation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.project.booking.stubs.Reservation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.project.booking.stubs.Reservation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message représentant une reservation
   * </pre>
   *
   * Protobuf type {@code Reservation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Reservation)
      com.project.booking.stubs.ReservationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.booking.stubs.ReservationOuterClass.internal_static_Reservation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.booking.stubs.ReservationOuterClass.internal_static_Reservation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.booking.stubs.Reservation.class, com.project.booking.stubs.Reservation.Builder.class);
    }

    // Construct using com.project.booking.stubs.Reservation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPreferencesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      dateDebut_ = "";

      dateFin_ = "";

      if (chambreBuilder_ == null) {
        chambre_ = null;
      } else {
        chambre_ = null;
        chambreBuilder_ = null;
      }
      if (clientBuilder_ == null) {
        client_ = null;
      } else {
        client_ = null;
        clientBuilder_ = null;
      }
      if (preferencesBuilder_ == null) {
        preferences_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        preferencesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.project.booking.stubs.ReservationOuterClass.internal_static_Reservation_descriptor;
    }

    @java.lang.Override
    public com.project.booking.stubs.Reservation getDefaultInstanceForType() {
      return com.project.booking.stubs.Reservation.getDefaultInstance();
    }

    @java.lang.Override
    public com.project.booking.stubs.Reservation build() {
      com.project.booking.stubs.Reservation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.project.booking.stubs.Reservation buildPartial() {
      com.project.booking.stubs.Reservation result = new com.project.booking.stubs.Reservation(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.dateDebut_ = dateDebut_;
      result.dateFin_ = dateFin_;
      if (chambreBuilder_ == null) {
        result.chambre_ = chambre_;
      } else {
        result.chambre_ = chambreBuilder_.build();
      }
      if (clientBuilder_ == null) {
        result.client_ = client_;
      } else {
        result.client_ = clientBuilder_.build();
      }
      if (preferencesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          preferences_ = java.util.Collections.unmodifiableList(preferences_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.preferences_ = preferences_;
      } else {
        result.preferences_ = preferencesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.project.booking.stubs.Reservation) {
        return mergeFrom((com.project.booking.stubs.Reservation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.project.booking.stubs.Reservation other) {
      if (other == com.project.booking.stubs.Reservation.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getDateDebut().isEmpty()) {
        dateDebut_ = other.dateDebut_;
        onChanged();
      }
      if (!other.getDateFin().isEmpty()) {
        dateFin_ = other.dateFin_;
        onChanged();
      }
      if (other.hasChambre()) {
        mergeChambre(other.getChambre());
      }
      if (other.hasClient()) {
        mergeClient(other.getClient());
      }
      if (preferencesBuilder_ == null) {
        if (!other.preferences_.isEmpty()) {
          if (preferences_.isEmpty()) {
            preferences_ = other.preferences_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePreferencesIsMutable();
            preferences_.addAll(other.preferences_);
          }
          onChanged();
        }
      } else {
        if (!other.preferences_.isEmpty()) {
          if (preferencesBuilder_.isEmpty()) {
            preferencesBuilder_.dispose();
            preferencesBuilder_ = null;
            preferences_ = other.preferences_;
            bitField0_ = (bitField0_ & ~0x00000001);
            preferencesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPreferencesFieldBuilder() : null;
          } else {
            preferencesBuilder_.addAllMessages(other.preferences_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.project.booking.stubs.Reservation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.project.booking.stubs.Reservation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object dateDebut_ = "";
    /**
     * <code>string dateDebut = 2;</code>
     * @return The dateDebut.
     */
    public java.lang.String getDateDebut() {
      java.lang.Object ref = dateDebut_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateDebut_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dateDebut = 2;</code>
     * @return The bytes for dateDebut.
     */
    public com.google.protobuf.ByteString
        getDateDebutBytes() {
      java.lang.Object ref = dateDebut_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateDebut_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dateDebut = 2;</code>
     * @param value The dateDebut to set.
     * @return This builder for chaining.
     */
    public Builder setDateDebut(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dateDebut_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dateDebut = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateDebut() {
      
      dateDebut_ = getDefaultInstance().getDateDebut();
      onChanged();
      return this;
    }
    /**
     * <code>string dateDebut = 2;</code>
     * @param value The bytes for dateDebut to set.
     * @return This builder for chaining.
     */
    public Builder setDateDebutBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dateDebut_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dateFin_ = "";
    /**
     * <code>string dateFin = 3;</code>
     * @return The dateFin.
     */
    public java.lang.String getDateFin() {
      java.lang.Object ref = dateFin_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateFin_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dateFin = 3;</code>
     * @return The bytes for dateFin.
     */
    public com.google.protobuf.ByteString
        getDateFinBytes() {
      java.lang.Object ref = dateFin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateFin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dateFin = 3;</code>
     * @param value The dateFin to set.
     * @return This builder for chaining.
     */
    public Builder setDateFin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dateFin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dateFin = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateFin() {
      
      dateFin_ = getDefaultInstance().getDateFin();
      onChanged();
      return this;
    }
    /**
     * <code>string dateFin = 3;</code>
     * @param value The bytes for dateFin to set.
     * @return This builder for chaining.
     */
    public Builder setDateFinBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dateFin_ = value;
      onChanged();
      return this;
    }

    private com.project.booking.stubs.Chambre chambre_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.project.booking.stubs.Chambre, com.project.booking.stubs.Chambre.Builder, com.project.booking.stubs.ChambreOrBuilder> chambreBuilder_;
    /**
     * <code>.Chambre chambre = 4;</code>
     * @return Whether the chambre field is set.
     */
    public boolean hasChambre() {
      return chambreBuilder_ != null || chambre_ != null;
    }
    /**
     * <code>.Chambre chambre = 4;</code>
     * @return The chambre.
     */
    public com.project.booking.stubs.Chambre getChambre() {
      if (chambreBuilder_ == null) {
        return chambre_ == null ? com.project.booking.stubs.Chambre.getDefaultInstance() : chambre_;
      } else {
        return chambreBuilder_.getMessage();
      }
    }
    /**
     * <code>.Chambre chambre = 4;</code>
     */
    public Builder setChambre(com.project.booking.stubs.Chambre value) {
      if (chambreBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        chambre_ = value;
        onChanged();
      } else {
        chambreBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Chambre chambre = 4;</code>
     */
    public Builder setChambre(
        com.project.booking.stubs.Chambre.Builder builderForValue) {
      if (chambreBuilder_ == null) {
        chambre_ = builderForValue.build();
        onChanged();
      } else {
        chambreBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Chambre chambre = 4;</code>
     */
    public Builder mergeChambre(com.project.booking.stubs.Chambre value) {
      if (chambreBuilder_ == null) {
        if (chambre_ != null) {
          chambre_ =
            com.project.booking.stubs.Chambre.newBuilder(chambre_).mergeFrom(value).buildPartial();
        } else {
          chambre_ = value;
        }
        onChanged();
      } else {
        chambreBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Chambre chambre = 4;</code>
     */
    public Builder clearChambre() {
      if (chambreBuilder_ == null) {
        chambre_ = null;
        onChanged();
      } else {
        chambre_ = null;
        chambreBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Chambre chambre = 4;</code>
     */
    public com.project.booking.stubs.Chambre.Builder getChambreBuilder() {
      
      onChanged();
      return getChambreFieldBuilder().getBuilder();
    }
    /**
     * <code>.Chambre chambre = 4;</code>
     */
    public com.project.booking.stubs.ChambreOrBuilder getChambreOrBuilder() {
      if (chambreBuilder_ != null) {
        return chambreBuilder_.getMessageOrBuilder();
      } else {
        return chambre_ == null ?
            com.project.booking.stubs.Chambre.getDefaultInstance() : chambre_;
      }
    }
    /**
     * <code>.Chambre chambre = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.project.booking.stubs.Chambre, com.project.booking.stubs.Chambre.Builder, com.project.booking.stubs.ChambreOrBuilder> 
        getChambreFieldBuilder() {
      if (chambreBuilder_ == null) {
        chambreBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.project.booking.stubs.Chambre, com.project.booking.stubs.Chambre.Builder, com.project.booking.stubs.ChambreOrBuilder>(
                getChambre(),
                getParentForChildren(),
                isClean());
        chambre_ = null;
      }
      return chambreBuilder_;
    }

    private com.project.booking.stubs.Client client_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.project.booking.stubs.Client, com.project.booking.stubs.Client.Builder, com.project.booking.stubs.ClientOrBuilder> clientBuilder_;
    /**
     * <code>.Client client = 5;</code>
     * @return Whether the client field is set.
     */
    public boolean hasClient() {
      return clientBuilder_ != null || client_ != null;
    }
    /**
     * <code>.Client client = 5;</code>
     * @return The client.
     */
    public com.project.booking.stubs.Client getClient() {
      if (clientBuilder_ == null) {
        return client_ == null ? com.project.booking.stubs.Client.getDefaultInstance() : client_;
      } else {
        return clientBuilder_.getMessage();
      }
    }
    /**
     * <code>.Client client = 5;</code>
     */
    public Builder setClient(com.project.booking.stubs.Client value) {
      if (clientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        client_ = value;
        onChanged();
      } else {
        clientBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Client client = 5;</code>
     */
    public Builder setClient(
        com.project.booking.stubs.Client.Builder builderForValue) {
      if (clientBuilder_ == null) {
        client_ = builderForValue.build();
        onChanged();
      } else {
        clientBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Client client = 5;</code>
     */
    public Builder mergeClient(com.project.booking.stubs.Client value) {
      if (clientBuilder_ == null) {
        if (client_ != null) {
          client_ =
            com.project.booking.stubs.Client.newBuilder(client_).mergeFrom(value).buildPartial();
        } else {
          client_ = value;
        }
        onChanged();
      } else {
        clientBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Client client = 5;</code>
     */
    public Builder clearClient() {
      if (clientBuilder_ == null) {
        client_ = null;
        onChanged();
      } else {
        client_ = null;
        clientBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Client client = 5;</code>
     */
    public com.project.booking.stubs.Client.Builder getClientBuilder() {
      
      onChanged();
      return getClientFieldBuilder().getBuilder();
    }
    /**
     * <code>.Client client = 5;</code>
     */
    public com.project.booking.stubs.ClientOrBuilder getClientOrBuilder() {
      if (clientBuilder_ != null) {
        return clientBuilder_.getMessageOrBuilder();
      } else {
        return client_ == null ?
            com.project.booking.stubs.Client.getDefaultInstance() : client_;
      }
    }
    /**
     * <code>.Client client = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.project.booking.stubs.Client, com.project.booking.stubs.Client.Builder, com.project.booking.stubs.ClientOrBuilder> 
        getClientFieldBuilder() {
      if (clientBuilder_ == null) {
        clientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.project.booking.stubs.Client, com.project.booking.stubs.Client.Builder, com.project.booking.stubs.ClientOrBuilder>(
                getClient(),
                getParentForChildren(),
                isClean());
        client_ = null;
      }
      return clientBuilder_;
    }

    private java.util.List<com.project.booking.stubs.Preference> preferences_ =
      java.util.Collections.emptyList();
    private void ensurePreferencesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        preferences_ = new java.util.ArrayList<com.project.booking.stubs.Preference>(preferences_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.project.booking.stubs.Preference, com.project.booking.stubs.Preference.Builder, com.project.booking.stubs.PreferenceOrBuilder> preferencesBuilder_;

    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public java.util.List<com.project.booking.stubs.Preference> getPreferencesList() {
      if (preferencesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(preferences_);
      } else {
        return preferencesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public int getPreferencesCount() {
      if (preferencesBuilder_ == null) {
        return preferences_.size();
      } else {
        return preferencesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public com.project.booking.stubs.Preference getPreferences(int index) {
      if (preferencesBuilder_ == null) {
        return preferences_.get(index);
      } else {
        return preferencesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public Builder setPreferences(
        int index, com.project.booking.stubs.Preference value) {
      if (preferencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePreferencesIsMutable();
        preferences_.set(index, value);
        onChanged();
      } else {
        preferencesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public Builder setPreferences(
        int index, com.project.booking.stubs.Preference.Builder builderForValue) {
      if (preferencesBuilder_ == null) {
        ensurePreferencesIsMutable();
        preferences_.set(index, builderForValue.build());
        onChanged();
      } else {
        preferencesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public Builder addPreferences(com.project.booking.stubs.Preference value) {
      if (preferencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePreferencesIsMutable();
        preferences_.add(value);
        onChanged();
      } else {
        preferencesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public Builder addPreferences(
        int index, com.project.booking.stubs.Preference value) {
      if (preferencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePreferencesIsMutable();
        preferences_.add(index, value);
        onChanged();
      } else {
        preferencesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public Builder addPreferences(
        com.project.booking.stubs.Preference.Builder builderForValue) {
      if (preferencesBuilder_ == null) {
        ensurePreferencesIsMutable();
        preferences_.add(builderForValue.build());
        onChanged();
      } else {
        preferencesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public Builder addPreferences(
        int index, com.project.booking.stubs.Preference.Builder builderForValue) {
      if (preferencesBuilder_ == null) {
        ensurePreferencesIsMutable();
        preferences_.add(index, builderForValue.build());
        onChanged();
      } else {
        preferencesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public Builder addAllPreferences(
        java.lang.Iterable<? extends com.project.booking.stubs.Preference> values) {
      if (preferencesBuilder_ == null) {
        ensurePreferencesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, preferences_);
        onChanged();
      } else {
        preferencesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public Builder clearPreferences() {
      if (preferencesBuilder_ == null) {
        preferences_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        preferencesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public Builder removePreferences(int index) {
      if (preferencesBuilder_ == null) {
        ensurePreferencesIsMutable();
        preferences_.remove(index);
        onChanged();
      } else {
        preferencesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public com.project.booking.stubs.Preference.Builder getPreferencesBuilder(
        int index) {
      return getPreferencesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public com.project.booking.stubs.PreferenceOrBuilder getPreferencesOrBuilder(
        int index) {
      if (preferencesBuilder_ == null) {
        return preferences_.get(index);  } else {
        return preferencesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public java.util.List<? extends com.project.booking.stubs.PreferenceOrBuilder> 
         getPreferencesOrBuilderList() {
      if (preferencesBuilder_ != null) {
        return preferencesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(preferences_);
      }
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public com.project.booking.stubs.Preference.Builder addPreferencesBuilder() {
      return getPreferencesFieldBuilder().addBuilder(
          com.project.booking.stubs.Preference.getDefaultInstance());
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public com.project.booking.stubs.Preference.Builder addPreferencesBuilder(
        int index) {
      return getPreferencesFieldBuilder().addBuilder(
          index, com.project.booking.stubs.Preference.getDefaultInstance());
    }
    /**
     * <pre>
     * Champ repeated pour les préférences
     * </pre>
     *
     * <code>repeated .Preference preferences = 6;</code>
     */
    public java.util.List<com.project.booking.stubs.Preference.Builder> 
         getPreferencesBuilderList() {
      return getPreferencesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.project.booking.stubs.Preference, com.project.booking.stubs.Preference.Builder, com.project.booking.stubs.PreferenceOrBuilder> 
        getPreferencesFieldBuilder() {
      if (preferencesBuilder_ == null) {
        preferencesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.project.booking.stubs.Preference, com.project.booking.stubs.Preference.Builder, com.project.booking.stubs.PreferenceOrBuilder>(
                preferences_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        preferences_ = null;
      }
      return preferencesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Reservation)
  }

  // @@protoc_insertion_point(class_scope:Reservation)
  private static final com.project.booking.stubs.Reservation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.project.booking.stubs.Reservation();
  }

  public static com.project.booking.stubs.Reservation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Reservation>
      PARSER = new com.google.protobuf.AbstractParser<Reservation>() {
    @java.lang.Override
    public Reservation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Reservation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Reservation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Reservation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.project.booking.stubs.Reservation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

