// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.project.booking.stubs;

public interface updateReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:updateReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ReservationDTO reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.ReservationDTO reservation = 1;</code>
   * @return The reservation.
   */
  com.project.booking.stubs.ReservationDTO getReservation();
  /**
   * <code>.ReservationDTO reservation = 1;</code>
   */
  com.project.booking.stubs.ReservationDTOOrBuilder getReservationOrBuilder();

  /**
   * <code>int64 id = 2;</code>
   * @return The id.
   */
  long getId();
}
